"""
act_config.py — generate act_config.yaml from a converted LeRobot dataset.

ACT training needs a handful of values that must match the dataset exactly:
chunk size, dataset frequency, the camera (image) keys, and the action/state
dimensions. Deriving them from meta/info.json (rather than hand-editing) keeps
training and deployment consistent with what was actually exported.

A tiny hand-rolled YAML writer is used so the repo gains no PyYAML dependency.
"""

from __future__ import annotations

import json
from pathlib import Path


def _yaml_scalar(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return v
    return str(v)


def _dump_yaml(d: dict, indent: int = 0) -> str:
    """Minimal YAML for flat dicts + lists of scalars + one-level nested dicts."""
    pad = "  " * indent
    lines: list[str] = []
    for k, v in d.items():
        if isinstance(v, dict):
            lines.append(f"{pad}{k}:")
            lines.append(_dump_yaml(v, indent + 1))
        elif isinstance(v, (list, tuple)):
            lines.append(f"{pad}{k}:")
            for item in v:
                lines.append(f"{pad}  - {_yaml_scalar(item)}")
        else:
            lines.append(f"{pad}{k}: {_yaml_scalar(v)}")
    return "\n".join(lines)


def build_act_config(info: dict, chunk_size: int, policy_freq: int) -> dict:
    """Derive an ACT config dict from a LeRobot info.json structure."""
    features = info.get("features", {})
    image_keys = [k for k in features if k.startswith("observation.images")]
    camera_names = [k.split(".")[-1] for k in image_keys]

    action_dim = int(features.get("action", {}).get("shape", [0])[0])
    state_dim  = int(features.get("observation.state", {}).get("shape", [0])[0])

    # Observation keys ACT will consume: proprio state + camera images + (optional)
    # cartesian eef streams if present in the dataset.
    obs_keys = ["observation.state"] + image_keys
    for extra in ("observation.eef_position", "observation.eef_orientation", "observation.eef_pose"):
        if extra in features:
            obs_keys.append(extra)

    dataset_hz = int(info.get("fps", 30))
    return {
        "dataset_hz": dataset_hz,
        "chunk_size": int(chunk_size),
        "recommended_policy_frequency": int(policy_freq),
        "action_dim": action_dim,
        "state_dim": state_dim,
        "camera_names": camera_names,
        "observation_keys": obs_keys,
        "robot_type": info.get("robot_type", "fr5"),
        "total_episodes": int(info.get("total_episodes", 0)),
        "total_frames": int(info.get("total_frames", 0)),
    }


def write_act_config(output_dir: Path, info: dict, chunk_size: int, policy_freq: int) -> Path:
    cfg = build_act_config(info, chunk_size, policy_freq)
    path = Path(output_dir) / "act_config.yaml"
    header = "# Auto-generated by convert_to_lerobot.py --act. Do not hand-edit;\n" \
             "# re-run the converter to regenerate from the dataset.\n"
    path.write_text(header + _dump_yaml(cfg) + "\n")
    return path


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description="Generate act_config.yaml from a LeRobot dataset.")
    ap.add_argument("--dataset", default="./lerobot_dataset", help="LeRobot dataset root")
    ap.add_argument("--chunk-size", type=int, default=50)
    ap.add_argument("--policy-freq", type=int, default=15)
    args = ap.parse_args()
    info = json.load(open(Path(args.dataset) / "meta" / "info.json"))
    out = write_act_config(Path(args.dataset), info, args.chunk_size, args.policy_freq)
    print(f"Wrote {out}")
